[project]
name = "aitest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "fedeteixeira", email = "fede150998@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "faker>=40.36.0",
    "groq>=1.6.0",
    "mysql-connector-python>=26.7.0",
    "pydantic>=2.13.4",
    "pydantic-ai>=2.27.0",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
]

[project.scripts]
aitest = "aitest:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.16.2",
]

[tool.ruff]
# Increase the maximum line length to 200 characters
line-length = 200

[tool.ruff.lint]
# Enable the standard pycodestyle (E), Pyflakes (F), and pep8-naming (N) rules
select = ["E", "F", "N"]
